Blog_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('account/', include('account.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html', success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), name='password_change_done'),
    path('password-reset', auth_views.PasswordResetView.as_view(template_name='account/password_reset.html', email_template_name='account/password_reset_email.html', success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html', success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete')
]

blog/urls.py
from django.urls import path, include
from . import views
from .feeds import PostRssFeed

# Contains All urls related to blog app

app_name = 'blog'

urlpatterns = [
    path('',views.post_list, name='blog_list'),
    path('tags/<slug:tag_slug>/',views.post_list, name='blog_list_by_tags'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', PostRssFeed(), name='post_feed'),
    path('search/', views.search, name='post_search'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):

    STATUS_CHOICE = (('draft','Draft'),('published','Published'),)
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()

    # Blog related dates

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICE, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    tags = TaggableManager()

# Model for Comments of the blog post

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms 
from .models import Comment

# Creating the forms for Share 

class EmailPostForm(forms.Form):    
    name = forms.CharField(max_length=25)    
    email = forms.EmailField()    
    to_email = forms.EmailField()    
    comments = forms.CharField(required=False, widget=forms.Textarea)

# Comment form 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count

# Blog home page for listing all published blogs

def post_list(request, tag_slug=None): 
    object_list = Post.published.all() 
    tag = None 
 
    if tag_slug: 
        tag = get_object_or_404(Tag, slug=tag_slug) 
        object_list = object_list.filter(tags__in=[tag]) 
 
    paginator = Paginator(object_list, 9) # 3 posts in each page 
    page = request.GET.get('page') 
    try: 
        posts = paginator.page(page) 
    except PageNotAnInteger: 
        # If page is not an integer deliver the first page 
        posts = paginator.page(1) 
    except EmptyPage: 
        # If page is out of range deliver last page of results 
        posts = paginator.page(paginator.num_pages) 
    return render(request, 'blog/blog_list.html', {'page': page, 'posts': posts, 'tag': tag}) 

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginated_by = 3
#     template_name = 'blog/blog_list.html'   

# Detailed post for individual blog

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status='published', publish__year=year, publish__month=month, publish__day=day, slug=post)

    # Collecting the comments to current post

    comments = post.comments.filter(is_active=True)

    new_comment = None
    if request.method == 'POST':
        # New comment has been made
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Save the comment but do not commit to database as still need to link post object
            new_comment = comment_form.save(commit=False)
            # Add current post to comment
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Suggesting post with similar tags
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]


    comment_form = CommentForm()
    context = { 'post':post,'comments':comments, 'comment_form':comment_form, 'new_comment':new_comment, 'similar_posts':similar_posts }
    return render(request, 'blog/post_detail.html', context)

# Sharing the post throgh Email using Forms

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')

    if request.method == 'POST':
        #Creatng the form from POST data
        form = EmailPostForm(request.POST)
        # Validating the Form
        if form.is_valid():
            # Cleaning the data
            cleaned_Form = form.cleaned_data
            # Sending post throgh mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} wants to share "{}"'.format(cleaned_Form['name'], post.title)
            message = '{} wants you read "{}" ({})\n\n Comments {}'.format(cleaned_Form['name'], post.title, post_url, cleaned_Form['comments'])
            send_mail(subject, message, 'kkthunga1@gmail.com', [cleaned_Form['to_email'],])
            sent = True
    else:
        # Displaying the emty form
        form = EmailPostForm()
        sent = False    
    context = { 'form':form, 'post':post, 'sent':sent }
    return render(request, 'blog/blog_share.html',context)
        
# Searching for posts in title and body

def search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            similar = TrigramSimilarity('title', query,)
            results = Post.objects.annotate(similarity=similar
                ).filter(similarity__gt=0.3).order_by('-similarity')

            # For searching across multiple fields

            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = Post.objects.annotate(search=search_vector, 
            #     rank=SearchRank(search_vector, search_query) ).filter(rank__gte=0.3).order_by('-rank')

    
    return render(request, 'blog/search.html', {'form':form, 'query':query, 'results':results})

blog/templates/blog/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
    <div>
        <h3>Latest posts</h3>
        {% show_latest_post %}
        <p>
            <a href = '{% url "blog:post_feed" %}'> Subsribe to my RSS feed </a>
        </p>
        <a href='{% url "blog:blog_list" %}'>Home</a>
        {% if user.is_authenticated %}
            <p>Hello, {{ user.username }}</p>
            <a href='{% url "account:dashboard" %}'>Dashboard</a>
            <a href='{% url "account:logout" %}'>Logout</a>
        {% else %}
            <a href='{% url "account:login" %}'>Login</a>
            <a href='#'>Register</a>
        {% endif %}
    </div>
    {% block content %} {% endblock %}
</body>
</html>

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if posts %}
        {% for post in posts %}
            <h2><a href="{{ post.get_absolute_url }}"> {{ post.title }} </a></h2>
                <p>
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:blog_list_by_tags" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
        {% endfor %}
    {% else %}
        <h2>No Published posts are available</h2>
    {% endif %}
{% endblock %}

blog/templates/blog/blog_share.html
{% extends 'blog/base.html' %}

{% block title %}Share Post{% endblock %}
{% block content%}  
    {% if sent %}
        <p>Post shared sucessfully </p>    
    {% else %}
        <p>Share {{ post.title }} by Email </p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    {% endif %}
    
{% endblock %}

blog/templates/blog/latest_post.html
<ul>
    {% for post in latest_post %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %} {{ post.title }}{% endblock %}

{% block content %}
    {% if post %}
       <h2>{{ post.title }}</h2>
       <p>Published by {{ post.author }} on {{ post.publish }}</p>
       <p>{{ post.body }}</p>
       <button><a href="{% url 'blog:post_share' post.id %}">Share this post</a></button>

        {% if comments %}
            {% with comments.count as total_comments %}
                <h2> 
                    {{ total_comments }} comment{{ total_comments|pluralize }}
                </h2>
            {% endwith %}
            {% for comment in comments %}
                <h3>{{ comment.name }} <span><h5>{{ comment.created }}</h5></span></h3>
                <p>{{ comment.body }}</p>
            {% endfor %}
        {% else %}
            <p>No comments yet</p>
        {% endif %}

        <div>
            {% if new_comment %}
                <p>Your comment is added </p>
                <form method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit">Comment</button>
                </form>
            {% else %}
                <h3>Add your comment here </h3>
                <form method="POST">
                    {% csrf_token %}
                    {{ comment_form.as_p }}
                    <button type="submit">Comment</button>
                </form>
            {% endif %}
        </div>

        <div>
            {% if similar_posts %}
                {% for post in similar_posts %}
                    <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                {% endfor %}
            {% else %}
                <p>No Similar posts</p>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% block content %}

{% if query %}
    {% if results %}
        <h2> Results for "{{ query }}"</h2>
        <h2>
            {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results | pluralize }}
            {% endwith %}
        </h2>
        {% for post in results %}
            <a href=" {{ 'post.get_absolute_url' }}">{{ post.title }}</a>
            <p>{{ post.body|truncatewords:5 }}</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h2> No results found for "{{ query }}"</h2>
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% endif %}

{% else %}
    <h2>Search for Post</h2>
    <form action='.' method="get">
        {% csrf_token %}
        {{ form.as_p }}
        <input type=submit value=Search >
    </form>    
{% endif %}

{% endblock %}